# Generated by Django 6.0.3 on 2026-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
