# Generated by Django 6.0.3 on 2026-04-18 20:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlavnaKnjiga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zakljucena",
                    models.BooleanField(default=False, verbose_name="Zaključena"),
                ),
                ("kreirana", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Glavna knjiga",
                "verbose_name_plural": "Glavne knjige",
            },
        ),
        migrations.CreateModel(
            name="GrupaArtikla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sifra",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Šifra grupe"
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="Naziv grupe")),
            ],
            options={
                "verbose_name": "Grupa artikla",
                "verbose_name_plural": "Grupe artikala",
                "ordering": ["sifra"],
            },
        ),
        migrations.CreateModel(
            name="JedinicaMjere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sifra",
                    models.CharField(max_length=10, unique=True, verbose_name="Šifra"),
                ),
                ("naziv", models.CharField(max_length=50, verbose_name="Naziv")),
            ],
            options={
                "verbose_name": "Jedinica mjere",
                "verbose_name_plural": "Jedinice mjere",
                "ordering": ["sifra"],
            },
        ),
        migrations.CreateModel(
            name="Konto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broj",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Broj konta"
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="Naziv konta")),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("aktiva", "Aktiva"),
                            ("pasiva", "Pasiva"),
                            ("prihod", "Prihod"),
                            ("rashod", "Rashod"),
                            ("izvanbil", "Izvanbilansna"),
                        ],
                        max_length=10,
                        verbose_name="Tip konta",
                    ),
                ),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
            ],
            options={
                "verbose_name": "Konto",
                "verbose_name_plural": "Konta",
                "ordering": ["broj"],
            },
        ),
        migrations.CreateModel(
            name="Porez",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=100, verbose_name="Naziv poreza"),
                ),
                (
                    "stopa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Stopa (%)",
                    ),
                ),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
            ],
            options={
                "verbose_name": "Porez",
                "verbose_name_plural": "Porezi",
                "ordering": ["stopa"],
            },
        ),
        migrations.CreateModel(
            name="PoslovnaGodina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("godina", models.IntegerField(unique=True, verbose_name="Godina")),
                ("aktivna", models.BooleanField(default=True, verbose_name="Aktivna")),
                (
                    "napomena",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Napomena"
                    ),
                ),
                ("kreirana", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Poslovna godina",
                "verbose_name_plural": "Poslovne godine",
                "ordering": ["-godina"],
            },
        ),
        migrations.CreateModel(
            name="PoslovniPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sifra",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Šifra partnera"
                    ),
                ),
                (
                    "naziv_1",
                    models.CharField(max_length=255, verbose_name="Naziv partnera (1)"),
                ),
                (
                    "naziv_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Naziv partnera (2)"
                    ),
                ),
                (
                    "ptt",
                    models.CharField(blank=True, max_length=10, verbose_name="PTT"),
                ),
                (
                    "mjesto",
                    models.CharField(blank=True, max_length=100, verbose_name="Mjesto"),
                ),
                (
                    "ulica",
                    models.CharField(blank=True, max_length=255, verbose_name="Ulica"),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=50, verbose_name="Fax"),
                ),
                (
                    "ziro_racun",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Žiro-račun"
                    ),
                ),
                (
                    "sifra_sjedista",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Šifra sjedišta"
                    ),
                ),
                (
                    "sinteticki_konto",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Sintetički konto"
                    ),
                ),
                (
                    "maticni_broj",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Matični broj"
                    ),
                ),
                (
                    "porezni_broj",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Porezni broj"
                    ),
                ),
                (
                    "broj_upisa_sud_reg",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Br. upisa u sud. reg."
                    ),
                ),
                (
                    "u_sustavu_pdv",
                    models.BooleanField(default=False, verbose_name="U sustavu PDV-a"),
                ),
                (
                    "entitet",
                    models.CharField(
                        choices=[("01", "FBiH"), ("02", "RS"), ("03", "Brčko")],
                        default="01",
                        max_length=2,
                        verbose_name="Entitet",
                    ),
                ),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
                ("kreiran", models.DateTimeField(auto_now_add=True)),
                ("izmijenjen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Poslovni partner",
                "verbose_name_plural": "Poslovni partneri",
                "ordering": ["sifra"],
            },
        ),
        migrations.CreateModel(
            name="Inventura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv inventure"),
                ),
                ("datum", models.DateField(verbose_name="Datum inventure")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("otvorena", "Otvorena"),
                            ("u_toku", "U toku"),
                            ("zakljucena", "Zaključena"),
                        ],
                        default="otvorena",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("napomena", models.TextField(blank=True, verbose_name="Napomena")),
                ("kreirano", models.DateTimeField(auto_now_add=True)),
                (
                    "zakljucena_u",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zaključena u"
                    ),
                ),
                (
                    "glavna_knjiga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventure",
                        to="a_home.glavnaknjiga",
                        verbose_name="Glavna knjiga",
                    ),
                ),
                (
                    "kreirao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kreirao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventura",
                "verbose_name_plural": "Inventure",
                "ordering": ["-datum"],
            },
        ),
        migrations.CreateModel(
            name="Knjizenje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(verbose_name="Datum")),
                ("opis", models.CharField(max_length=500, verbose_name="Opis")),
                (
                    "dokument_broj",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Broj dokumenta"
                    ),
                ),
                ("kreirano", models.DateTimeField(auto_now_add=True)),
                ("izmijenjeno", models.DateTimeField(auto_now=True)),
                (
                    "glavna_knjiga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knjizenja",
                        to="a_home.glavnaknjiga",
                        verbose_name="Glavna knjiga",
                    ),
                ),
                (
                    "kreirao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kreirao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knjiženje",
                "verbose_name_plural": "Knjiženja",
                "ordering": ["-datum", "-kreirano"],
            },
        ),
        migrations.CreateModel(
            name="Artikal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sifra",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Šifra artikla"
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="Naziv artikla"),
                ),
                (
                    "cijena",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Cijena",
                    ),
                ),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
                ("kreiran", models.DateTimeField(auto_now_add=True)),
                ("izmijenjen", models.DateTimeField(auto_now=True)),
                (
                    "grupa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_home.grupaartikla",
                        verbose_name="Grupa",
                    ),
                ),
                (
                    "jedinica_mjere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_home.jedinicamjere",
                        verbose_name="Jedinica mjere",
                    ),
                ),
                (
                    "porez",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_home.porez",
                        verbose_name="Porez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikal",
                "verbose_name_plural": "Artikli",
                "ordering": ["sifra"],
            },
        ),
        migrations.AddField(
            model_name="glavnaknjiga",
            name="godina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="glavne_knjige",
                to="a_home.poslovnagodina",
                verbose_name="Godina",
            ),
        ),
        migrations.AddField(
            model_name="glavnaknjiga",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="glavne_knjige",
                to="a_home.poslovnipartner",
                verbose_name="Partner",
            ),
        ),
        migrations.CreateModel(
            name="PrenosStanja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("priprema", "U pripremi"),
                            ("izvrseno", "Izvršeno"),
                            ("greska", "Greška"),
                        ],
                        default="priprema",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "broj_stavki",
                    models.IntegerField(
                        default=0, verbose_name="Broj prenesenih stavki"
                    ),
                ),
                ("kreirano", models.DateTimeField(auto_now_add=True)),
                ("napomena", models.TextField(blank=True, verbose_name="Napomena")),
                (
                    "iz_godine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prenosi_iz",
                        to="a_home.poslovnagodina",
                        verbose_name="Iz godine",
                    ),
                ),
                (
                    "knjizenje",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_home.knjizenje",
                        verbose_name="Knjiženje prenosa",
                    ),
                ),
                (
                    "kreirao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kreirao",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.poslovnipartner",
                        verbose_name="Partner",
                    ),
                ),
                (
                    "u_godinu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prenosi_u",
                        to="a_home.poslovnagodina",
                        verbose_name="U godinu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prenos stanja",
                "verbose_name_plural": "Prenosi stanja",
                "ordering": ["-kreirano"],
            },
        ),
        migrations.CreateModel(
            name="StavkaKnjizenja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opis",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Opis stavke"
                    ),
                ),
                (
                    "duguje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Duguje",
                    ),
                ),
                (
                    "potrazuje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Potražuje",
                    ),
                ),
                (
                    "knjizenje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="a_home.knjizenje",
                        verbose_name="Knjiženje",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.konto",
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka knjiženja",
                "verbose_name_plural": "Stavke knjiženja",
            },
        ),
        migrations.AlterUniqueTogether(
            name="glavnaknjiga",
            unique_together={("partner", "godina")},
        ),
        migrations.CreateModel(
            name="SaldoKonta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duguje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Duguje",
                    ),
                ),
                (
                    "potrazuje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Potražuje",
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Saldo"
                    ),
                ),
                (
                    "preneseno",
                    models.BooleanField(
                        default=False, verbose_name="Preneseno u novu godinu"
                    ),
                ),
                (
                    "datum_prenosa",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Datum prenosa"
                    ),
                ),
                (
                    "glavna_knjiga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salda",
                        to="a_home.glavnaknjiga",
                        verbose_name="Glavna knjiga",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.konto",
                        verbose_name="Konto",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_home.poslovnipartner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo konta",
                "verbose_name_plural": "Salda konta",
                "ordering": ["konto__broj"],
                "unique_together": {("glavna_knjiga", "konto", "partner")},
            },
        ),
        migrations.CreateModel(
            name="StavkaInventure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kolicina_knjig",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Količina po knjizi",
                    ),
                ),
                (
                    "cijena_knjig",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Cijena po knjizi",
                    ),
                ),
                (
                    "kolicina_popis",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Količina po popisu",
                    ),
                ),
                (
                    "cijena_popis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Cijena po popisu",
                    ),
                ),
                (
                    "napomena",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Napomena"
                    ),
                ),
                (
                    "artikal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.artikal",
                        verbose_name="Artikal",
                    ),
                ),
                (
                    "inventura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="a_home.inventura",
                        verbose_name="Inventura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka inventure",
                "verbose_name_plural": "Stavke inventure",
                "ordering": ["artikal__sifra"],
                "unique_together": {("inventura", "artikal")},
            },
        ),
    ]
