# Generated by Django 6.0.3 on 2026-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knjizenje",
            name="broj_naloga",
            field=models.IntegerField(default=1, verbose_name="Broj naloga"),
        ),
        migrations.AlterUniqueTogether(
            name="knjizenje",
            unique_together={("glavna_knjiga", "broj_naloga")},
        ),
    ]
