# Generated by Django 6.0.3 on 2026-04-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0002_knjizenje_broj_naloga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SintetickiKonto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="Naziv")),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
                ("kreiran", models.DateTimeField(auto_now_add=True)),
                (
                    "glavna_knjiga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sinteticki_konti",
                        to="a_home.glavnaknjiga",
                        verbose_name="Glavna knjiga",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.konto",
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sintetički konto",
                "verbose_name_plural": "Sintetički konti",
                "ordering": ["konto__broj"],
                "unique_together": {("glavna_knjiga", "konto")},
            },
        ),
        migrations.CreateModel(
            name="AnalitickiKonto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sifra", models.CharField(max_length=20, verbose_name="Šifra")),
                ("naziv", models.CharField(max_length=255, verbose_name="Naziv")),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
                ("kreiran", models.DateTimeField(auto_now_add=True)),
                (
                    "glavna_knjiga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analiticki_konti",
                        to="a_home.glavnaknjiga",
                        verbose_name="Glavna knjiga",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_home.poslovnipartner",
                        verbose_name="Partner",
                    ),
                ),
                (
                    "sinteticki_konto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analitika",
                        to="a_home.sintetickikonto",
                        verbose_name="Sintetički konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analitički konto",
                "verbose_name_plural": "Analitički konti",
                "ordering": ["sifra"],
                "unique_together": {("glavna_knjiga", "sifra")},
            },
        ),
    ]
