# Generated by Django 6.0.3 on 2026-04-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0003_sintetickikonto_analitickikonto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kalkulacija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primalac",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Primalac"
                    ),
                ),
                (
                    "broj_prij_lista",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Broj prijemnog lista"
                    ),
                ),
                (
                    "datum_prij_lista",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum prijemnog lista"
                    ),
                ),
                (
                    "dokument",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dokument"
                    ),
                ),
                (
                    "datum_dokumenta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum dokumenta"
                    ),
                ),
                (
                    "datum_dospijeca",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum dospijeća"
                    ),
                ),
                (
                    "datum_prijema",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum prijema"
                    ),
                ),
                (
                    "knjiga",
                    models.CharField(
                        default="01", max_length=10, verbose_name="Knjiga"
                    ),
                ),
                (
                    "kuf",
                    models.CharField(blank=True, max_length=50, verbose_name="KUF"),
                ),
                (
                    "iznos_racuna",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Iznos računa",
                    ),
                ),
                (
                    "iznos_pdv",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Iznos PDV-a",
                    ),
                ),
                (
                    "pdv_za_odbiti",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="PDV za odbiti",
                    ),
                ),
                (
                    "pdv_ne_odbiti",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="PDV ne odbiti",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("otvorena", "Otvorena"),
                            ("zakljucena", "Zaključena"),
                        ],
                        default="otvorena",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("kreirano", models.DateTimeField(auto_now_add=True)),
                ("izmijenjeno", models.DateTimeField(auto_now=True)),
                (
                    "dobavljac",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kalkulacije_dobavljac",
                        to="a_home.poslovnipartner",
                        verbose_name="Dobavljač",
                    ),
                ),
                (
                    "godina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.poslovnagodina",
                        verbose_name="Godina",
                    ),
                ),
                (
                    "kreirao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kreirao",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kalkulacije",
                        to="a_home.poslovnipartner",
                        verbose_name="Firma/Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalkulacija",
                "verbose_name_plural": "Kalkulacije",
                "ordering": ["-kreirano"],
            },
        ),
        migrations.CreateModel(
            name="StavkaKalkulacije",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porezna_grupa",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Porezna grupa"
                    ),
                ),
                (
                    "naziv_artikla",
                    models.CharField(max_length=255, verbose_name="Naziv artikla"),
                ),
                (
                    "jedinica_mjere",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Jedinica mjere"
                    ),
                ),
                (
                    "kolicina",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Količina",
                    ),
                ),
                (
                    "fakturna_cijena",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Fakturna cijena",
                    ),
                ),
                (
                    "nabavna_cijena",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Nabavna cijena",
                    ),
                ),
                (
                    "marza_postotak",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Marža %",
                    ),
                ),
                (
                    "marza_vrijednost",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="Marža vrijednost",
                    ),
                ),
                (
                    "porez",
                    models.CharField(default="P", max_length=10, verbose_name="Porez"),
                ),
                (
                    "mpc",
                    models.DecimalField(
                        decimal_places=3, default=0, max_digits=15, verbose_name="MPC"
                    ),
                ),
                (
                    "kalkulacija",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="a_home.kalkulacija",
                        verbose_name="Kalkulacija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka kalkulacije",
                "verbose_name_plural": "Stavke kalkulacije",
            },
        ),
    ]
