# Generated by Django 6.0.3 on 2026-04-22 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0004_kalkulacija_stavkakalkulacije"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KorisnickePostavke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pozadina",
                    models.CharField(
                        default="pozadina.png",
                        max_length=100,
                        verbose_name="Pozadinska slika",
                    ),
                ),
                (
                    "korisnik",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postavke",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Korisničke postavke",
            },
        ),
    ]
