# Generated by Django 6.0.3 on 2026-04-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0005_korisnickepostavke"),
    ]

    operations = [
        migrations.AddField(
            model_name="stavkaknjizenja",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="a_home.poslovnipartner",
                verbose_name="Partner",
            ),
        ),
    ]
