# Generated by Django 6.0.3 on 2026-07-05 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0006_stavkaknjizenja_partner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObracunPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mjesec", models.IntegerField(verbose_name="Mjesec")),
                (
                    "naziv",
                    models.CharField(blank=True, max_length=255, verbose_name="Naziv"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("nacrt", "Nacrt"), ("zakljucen", "Zaključen")],
                        default="nacrt",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("kreirano", models.DateTimeField(auto_now_add=True)),
                (
                    "godina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.poslovnagodina",
                        verbose_name="Godina",
                    ),
                ),
                (
                    "kreirao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kreirao",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obracuni_placa",
                        to="a_home.poslovnipartner",
                        verbose_name="Firma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obračun plaća",
                "verbose_name_plural": "Obračuni plaća",
                "ordering": ["-godina__godina", "-mjesec"],
                "unique_together": {("partner", "godina", "mjesec")},
            },
        ),
        migrations.CreateModel(
            name="Zaposlenik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jmb",
                    models.CharField(blank=True, max_length=13, verbose_name="JMB"),
                ),
                ("ime", models.CharField(max_length=100, verbose_name="Ime")),
                ("prezime", models.CharField(max_length=100, verbose_name="Prezime")),
                (
                    "adresa",
                    models.CharField(blank=True, max_length=255, verbose_name="Adresa"),
                ),
                (
                    "sifra_opcine",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Šifra općine"
                    ),
                ),
                (
                    "pozicija",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Radno mjesto"
                    ),
                ),
                (
                    "datum_zaposlenja",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum zaposlenja"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("aktivan", "Aktivan"), ("neaktivan", "Neaktivan")],
                        default="aktivan",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "kf_licnog_odbitka",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=4,
                        verbose_name="Kf ličnog odbitka",
                    ),
                ),
                ("kreiran", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaposlenici",
                        to="a_home.poslovnipartner",
                        verbose_name="Firma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaposlenik",
                "verbose_name_plural": "Zaposlenici",
                "ordering": ["prezime", "ime"],
            },
        ),
        migrations.CreateModel(
            name="StavkaObracuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "radni_sati",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Radni sati",
                    ),
                ),
                (
                    "sati_bolovanja",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Sati bolovanja",
                    ),
                ),
                (
                    "bruto_placa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Bruto plaća",
                    ),
                ),
                (
                    "druge_koristi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Druge koristi",
                    ),
                ),
                (
                    "datum_isplate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Datum isplate"
                    ),
                ),
                (
                    "napomena",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Napomena"
                    ),
                ),
                (
                    "obracun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke",
                        to="a_home.obracunplace",
                        verbose_name="Obračun",
                    ),
                ),
                (
                    "zaposlenik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.zaposlenik",
                        verbose_name="Zaposlenik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka obračuna",
                "verbose_name_plural": "Stavke obračuna",
                "ordering": ["zaposlenik__prezime"],
                "unique_together": {("obracun", "zaposlenik")},
            },
        ),
    ]
