# Generated by Django 6.0.3 on 2026-07-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0007_obracunplace_zaposlenik_stavkaobracuna"),
    ]

    operations = [
        migrations.AddField(
            model_name="poslovnipartner",
            name="firma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partneri_firme",
                to="a_home.poslovnipartner",
                verbose_name="Pripada firmi",
            ),
        ),
        migrations.CreateModel(
            name="PartnerFirme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
                ("kreiran", models.DateTimeField(auto_now_add=True)),
                (
                    "firma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kao_firma",
                        to="a_home.poslovnipartner",
                        verbose_name="Firma",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kao_partner_firme",
                        to="a_home.poslovnipartner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner firme",
                "verbose_name_plural": "Partneri firme",
                "unique_together": {("firma", "partner")},
            },
        ),
    ]
