# Generated by Django 6.0.3 on 2026-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0008_poslovnipartner_firma_partnerfirme"),
    ]

    operations = [
        migrations.AddField(
            model_name="poslovnipartner",
            name="pdv_broj",
            field=models.CharField(blank=True, max_length=12, verbose_name="PDV broj"),
        ),
    ]
