# Generated by Django 6.0.3 on 2026-07-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0009_poslovnipartner_pdv_broj"),
    ]

    operations = [
        migrations.AddField(
            model_name="poslovnipartner",
            name="jib",
            field=models.CharField(blank=True, max_length=13, verbose_name="JIB/JMB"),
        ),
        migrations.AddField(
            model_name="poslovnipartner",
            name="sifra_djelatnosti",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Šifra djelatnosti"
            ),
        ),
    ]
