# Generated by Django 6.0.3 on 2026-07-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0010_poslovnipartner_jib_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VrstaIsplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sifra", models.CharField(max_length=10, verbose_name="Šifra")),
                ("naziv", models.CharField(max_length=100, verbose_name="Naziv")),
                (
                    "koeficijent",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="Koeficijent",
                    ),
                ),
                (
                    "obracunava_doprinose",
                    models.BooleanField(
                        default=True, verbose_name="Doprinosi se obračunavaju"
                    ),
                ),
                ("aktivan", models.BooleanField(default=True, verbose_name="Aktivan")),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vrste_isplate",
                        to="a_home.poslovnipartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vrsta isplate",
                "verbose_name_plural": "Vrste isplate",
                "ordering": ["sifra"],
                "unique_together": {("partner", "sifra")},
            },
        ),
        migrations.CreateModel(
            name="StavkaVrsteIsplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sati",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "iznos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "stavka_obracuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vrste",
                        to="a_home.stavkaobracuna",
                    ),
                ),
                (
                    "vrsta_isplate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.vrstaisplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka vrste isplate",
            },
        ),
    ]
