# Generated by Django 6.0.3 on 2026-07-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_home", "0011_vrstaisplate_stavkavrsteisplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="StavkaZarade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sati",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Sati"
                    ),
                ),
                (
                    "postotak",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Postotak",
                    ),
                ),
                (
                    "iznos",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Iznos"
                    ),
                ),
                (
                    "stavka_obracuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stavke_zarade",
                        to="a_home.stavkaobracuna",
                        verbose_name="Stavka obračuna",
                    ),
                ),
                (
                    "vrsta_isplate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="a_home.vrstaisplate",
                        verbose_name="Vrsta isplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka zarade",
                "verbose_name_plural": "Stavke zarade",
                "ordering": ["vrsta_isplate__sifra"],
            },
        ),
    ]
